#!/bin/sh
set -eu
set -f
LC_ALL=C
export LC_ALL
fail(){ printf '%s\n' "INTAKE_ERROR: $*" >&2;exit 1; }
arg(){ k=$1;shift;while [ "$#" -gt 1 ];do [ "$1" = "$k" ]&&{ printf '%s\n' "$2";return;};shift;done;fail "missing option: $k"; }
canon(){ if [ -d "$1" ];then(cd "$1"&&pwd -P);else d=$(dirname "$1");b=$(basename "$1");printf '%s/%s\n' "$(cd "$d"&&pwd -P)" "$b";fi; }
inside(){ case "$1/" in "$2"/*) return 0;;*) return 1;;esac; }
hash(){ if command -v sha256sum >/dev/null 2>&1;then sha256sum < "$1"|awk '{print $1}';elif command -v shasum >/dev/null 2>&1;then shasum -a 256 < "$1"|awk '{print $1}';elif command -v openssl >/dev/null 2>&1;then openssl dgst -sha256 < "$1"|awk '{print $NF}';else fail 'no SHA-256 provider';fi; }
manifest(){ root=$1;out=$2;if [ -f "$root" ];then printf '%s  %s\n' "$(hash "$root")" "$(basename "$root")">"$out";return;fi;find "$root" \( -type l -o -name .git -o -name .agent-state -o -name .agent-work -o -name .agent-protocol -o -name tasks \) -prune -o -type f -print | while IFS= read -r f;do rel=${f#"$root"/};printf '%s  %s\n' "$(hash "$f")" "$rel";done|sort>"$out"; }
copy_input(){ workspace_arg=$1;task_arg=$2;source_arg=$3;[ ! -L "$workspace_arg" ]&&[ ! -L "$task_arg" ]&&[ ! -L "$source_arg" ]||fail 'symlink source or destination rejected';w=$(canon "$workspace_arg");t=$(canon "$task_arg");s=$(canon "$source_arg");inside "$t" "$w"||fail 'Task outside workspace';if inside "$s" "$t";then printf '%s\n' "INPUT_ALREADY_IN_TASK $s";return;fi;if [ -d "$s" ];then case "$(basename "$s")" in .git|.agent-state|.agent-work|.agent-protocol|tasks) fail 'protected source directory rejected';;esac;fi;if [ -d "$s" ]&&find "$s" -type l -print -quit|grep -q .;then fail 'symlink in source tree rejected';fi;input="$t/UserInput";mkdir -p "$input";n=1;while [ -e "$input/I-$(printf '%04d' "$n")" ];do n=$((n+1));done;id="I-$(printf '%04d' "$n")";batch="$input/$id";mkdir "$batch"
  if [ -d "$s" ];then dest="$batch/$(basename "$s")";mkdir "$dest";(cd "$s"&&find . \( -type l -o -name .git -o -name .agent-state -o -name .agent-work -o -name .agent-protocol -o -name tasks \) -prune -o -type d -exec mkdir -p "$dest/{}" \; -o -type f -exec cp -p "{}" "$dest/{}" \;);else dest="$batch";cp -p "$s" "$dest/";fi
  compare="$w/.agent-work/.txn/intake.$$";manifest "$s" "$compare.source";manifest "$dest" "$compare.copy";cmp -s "$compare.source" "$compare.copy"||{ rm -f "$compare.source" "$compare.copy";fail 'tree diff is not empty';};count=$(wc -l<"$compare.source"|tr -d ' ');rm -f "$compare.source" "$compare.copy";inside "$s" "$w"&&scope=WORKSPACE||scope=EXTERNAL;printf '%s\n' "INPUT_IMPORT_VERIFIED $id" "SOURCE_SCOPE: $scope" "SOURCE: $s" "DESTINATION: $dest" "FILE_COUNT: $count";[ "$scope" = WORKSPACE ]&&printf '%s\n' DELETE_SOURCE_OPTION_AVAILABLE||printf '%s\n' SOURCE_PRESERVED
}
delete_source(){ workspace_arg=$1;task_arg=$2;source_arg=$3;copy_arg=$4;[ ! -L "$workspace_arg" ]&&[ ! -L "$task_arg" ]&&[ ! -L "$source_arg" ]&&[ ! -L "$copy_arg" ]||fail 'symlink source or destination rejected';w=$(canon "$workspace_arg");t=$(canon "$task_arg");s=$(canon "$source_arg");c=$(canon "$copy_arg");inside "$s" "$w"||fail 'external source deletion forbidden';inside "$s" "$t"&&fail 'Task source deletion forbidden';tmp=${TMPDIR:-/tmp}/intake.$$;manifest "$s" "$tmp.s";manifest "$c" "$tmp.c";cmp -s "$tmp.s" "$tmp.c"||{ rm -f "$tmp.s" "$tmp.c";fail 'source changed';};rm -f "$tmp.s" "$tmp.c";if [ -d "$s" ];then rm -rf -- "$s";else rm -f -- "$s";fi;[ ! -e "$s" ]||fail 'source deletion incomplete';printf '%s\n' "INPUT_SOURCE_DELETED $s"; }
[ "$#" -ge 1 ]||fail 'usage: intake <copy|delete>';cmd=$1;shift
case "$cmd" in copy)copy_input "$(arg --workspace-root "$@")" "$(arg --task-root "$@")" "$(arg --source "$@")";;delete)delete_source "$(arg --workspace-root "$@")" "$(arg --task-root "$@")" "$(arg --source "$@")" "$(arg --copy "$@")";;*)fail 'unknown command';;esac
